plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

application {
    mainClass = 'Main'
}

version '1.0'

sourceCompatibility = 17
targetCompatibility = 17



repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'net.dv8tion:JDA:6.4.1'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
    implementation 'com.github.DiscordBotList:DBL-Java-Library:2.0.1'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.konghq:unirest-java:3.4.00'
    implementation 'club.minnced:discord-webhooks:0.8.4'
    implementation 'commons-io:commons-io:2.15.1'
    implementation 'org.apache.commons:commons-lang3:3.14.0'
    implementation 'com.googlecode.json-simple:json-simple:1.1.1'
}


compileJava.options.encoding = 'UTF-8'
